name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build with dotnet
      run: dotnet build --configuration Release

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment variables
      run: |
        echo "DB_SERVER=${{ secrets.DB_SERVER }}" >> $env:GITHUB_ENV
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> $env:GITHUB_ENV
        echo "DB_USER=${{ secrets.DB_USER }}" >> $env:GITHUB_ENV
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $env:GITHUB_ENV
        echo "SMTP_SERVER=${{ secrets.SMTP_SERVER }}" >> $env:GITHUB_ENV
        echo "SMTP_SENDER_NAME=${{ secrets.SMTP_SENDER_NAME }}" >> $env:GITHUB_ENV
        echo "SMTP_SENDER_EMAIL=${{ secrets.SMTP_SENDER_EMAIL }}" >> $env:GITHUB_ENV
        echo "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" >> $env:GITHUB_ENV
        echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> $env:GITHUB_ENV

    - name: Install gettext
      run: winget install -e --id GnuWin32.gettext

    - name: Replace environment variables in appsettings.Production.json
      run: |
        envsubst < HttpWebshopCookie/appsettings.Production.json > HttpWebshopCookie/appsettings.Production.json.tmp
        mv HttpWebshopCookie/appsettings.Production.json.tmp HttpWebshopCookie/appsettings.Production.json
      shell: bash

    - name: Publish application
      run: dotnet publish --configuration Release --output ./publish

    - name: Deploy application
      run: ./scripts/deploy-script.ps1
      shell: pwsh
      env:
        DB_SERVER: ${{ secrets.DB_SERVER }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_SENDER_NAME: ${{ secrets.SMTP_SENDER_NAME }}
        SMTP_SENDER_EMAIL: ${{ secrets.SMTP_SENDER_EMAIL }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
